version: '2.1'
services:
  config-server:
    build: config-server
    mem_limit: 200000000
    ports:
      - 8888:8888

  api-gateway:
    build: api-gateway
    mem_limit: 200000000
    ports:
      - 8080:8080
    depends_on:
      config-server:
        condition: service_healthy

  inventory-service:
    build: inventory-service
    mem_limit: 200000000
    ports:
      - 8081:8081
    depends_on:
      config-server:
        condition: service_healthy
